### ISSUE TITLE
Add support for Equinix Metal Metros

### ISSUE THREAD

**Issue by displague** [equinix/ansible-collection-metal#30]
Equinix Metal facilities can now be treated as aggregate, in many ways, using metros:
* https://feedback.equinixmetal.com/changelog/new-metros-feature-live

### TODO
_(add more or sub-levels as needed)_
  * [ ] Introduce a new metro_info [module](https://github.com/equinix/ansible-collection-metal/tree/main/plugins/modules)
  * [ ] Introduce Metro features where applicable (info, inventory, and managing modules):
    * [ ] Facilities (now include a `metro` field)
    * [ ] Plans (now include `available_in_metros`)
    * [ ] Capacity Info (now has a separate `/capacity/metros` GET/POST endpoint)
    * [ ] Devices (now include a `metro` field)
    * [ ] VLANs (may include a `metro` field)
    * (N/A, not implemented in Ansible) Hardware Reservation, Batch, SpotMarket, SpotMarketPrices
    * (N/A, not implemented in packet-python) Connections (https://github.com/packethost/packet-python/issues/111),  IP reservations (https://github.com/packethost/packet-python/issues/109)
    * (N/A, not metro-enabled) Volumes (also not in Ansible)

When provisioning these resources, either a `facility` or a `metro` parameter should be provided.

Device and IP Address responses, for existing resources, will return both `facility` and `metro` responses.
VLAN resources will only return a `metro` or `facility` (along with metro_code, facility_code) depending on how they were provisioned.

Depends on https://github.com/packethost/packet-python/issues/108

**Comment by dlotterman** [comment]
Just commenting for the transcript that the Facility / Metro handling in the IP reservations context (cited above or [here](https://github.com/equinix/ansible-collection-metal/issues/30#issue-860344125))  is currently causing flakey user behavior. 

I'll try to capture the notes to reproduce / document shortly.
